version: 2.1

commands:
  restore_npm_cache:
    description: 'Restore npm cache'
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
  save_npm_cache:
    description: 'Save npm cache'
    steps:
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

jobs:
  build_test:
    parallelism: 1
    docker:
      - image: circleci/node:12.13-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_npm_cache
      - run: npm install
      - run: npm audit
      - run: npm rebuild node-sass
      - run: npm run-script test_without_watch
      # - run: npm run-script e2e
      - run: npm run-script coveralls
      - store_artifacts:
          path: ~/repo/coverage
          destination: coverage

  deploy:
    parallelism: 1
    docker:
      - image: circleci/node:12.13-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_npm_cache
      - run: git config --global user.name $GIT_USER_NAME
      - run: git config --global user.email $GIT_USER_EMAIL
      - run: npm run-script build:prod
      - run: npm run-script deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_test:
          filters:
            branches:
              ignore:
                - master
                - gh-pages
      - deploy:
          filters:
            branches:
              only: master
