version: 2.1

commands:
  restore_npm_cache:
    description: 'Restore npm cache'
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
  save_npm_cache:
    description: 'Save npm cache'
    steps:
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/node:12.13-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_npm_cache
      - run: npm install
      - run: npm audit
      - run: npm rebuild node-sass
      - save_npm_cache

  test:
    parallelism: 1
    docker:
      - image: circleci/node:12.13-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: node_modules/protractor/bin/webdriver-manager update --versions.chrome 79.0.3945.36
      - run: npm run-script test_without_watch
      - run: npm run-script e2e
      - run: npm run-script coveralls
      - store_artifacts:
          path: ~/repo/coverage
          destination: coverage

  deploy:
    parallelism: 1
    docker:
      - image: circleci/node:12.13-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_npm_cache
      - run: npm run-script deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
