version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.6

executors:
  default:
    docker:
      - image: cimg/node:21.4.0-browsers
        auth:
          username: nayoro84
          password: $DOCKERHUB_ACCESS_TOKEN

commands:
  restore_npm_cache:
    description: 'Restore npm cache'
    steps:
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package-lock.json" }}
            - v2-dependencies-
  save_npm_cache:
    description: 'Save npm cache'
    steps:
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package-lock.json" }}

jobs:
  deploy:
    executor: default
    parallelism: 1
    working_directory: ~/repo
    steps:
      - browser-tools/install-browser-tools
      - run: rm -rf *
      - checkout
      - restore_npm_cache
      - run: npm install
      - run: git config --global user.name $GIT_USER_NAME
      - run: git config --global user.email $GIT_USER_EMAIL
      - run: npm run deploy

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
